name: Native AOT

on:
  push:
    branches:
      - "main"

jobs:
  aot-test:
    name: Native AOT Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Publish (Native AOT)
        run: >
          dotnet publish tests/Umbrace.Totp.Tests/Umbrace.Totp.Tests.csproj
          --configuration Release
          --runtime linux-x64
          --output publish
          /p:PublishAot=true

      - name: Run AOT tests
        run: ./publish/Umbrace.Totp.Tests
